### ISSUE TITLE
Book VS Source Code

### ISSUE THREAD

**Issue by detectedstealth** [PacktPublishing/Hands-On-Swift-5-Microservices-Development#1]
Issue: I have been going through your new book, however am completely lost because the book has incomplete examples and when looking at the source code it doesn't match what is in the book.

Some of the code on here is still using Vapor 3, other chapters are completely empty. The chapter on building the template and the source found here is incomplete.

Is this still a work in progress?

**Comment by proggeramlug** [comment]
Hey, 

I'm so sorry, some chapter folders were severely out of date. The book was written as Vapor 4 was still in Alpha, so certain parts of it were originally Vapor 3 but have since been updated to Vapor 4.

I just pushed the most recent updates that contain all Vapor 4 and are working with the beta. Let me know if you encounter any problems there!

**Comment by proggeramlug** [comment]
@detectedstealth As a note though: As Vapor develops there _might_ be some minor issues with the code that you find in the book and what Vapor expects. We are updating the book when Vapor 4 is fully released.

In the meantime, I'm doing my best to keep this code here in Github up to date with Vapor 4. Ping me if you find something not making sense.

I appreciate all the feedback!
